const questions = [

  // ── GENERAL (100 questions) ──────────────────────────────────────
  // --- Already established ---
  {"text": "The Library of Alexandria was most likely destroyed by:", "options": ["Julius Caesar", "A single catastrophic fire", "Multiple events over centuries", "The Arab conquest"], "correct": 2, "level": 1},
  {"text": "Which country used pink as a military camouflage colour during World War II?", "options": ["Italy", "Germany", "United Kingdom", "United States"], "correct": 2, "level": 1},
  {"text": "Napoleon Bonaparte was actually quite short for his time. True or false?", "options": ["True", "False"], "correct": 1, "level": 1},
  {"text": "Which ancient civilization invented the concept of the 24-hour day?", "options": ["Greeks", "Romans", "Egyptians", "Babylonians"], "correct": 3, "level": 1},
  {"text": "The Great Wall of China is visible from space with the naked eye. True or false?", "options": ["True", "False"], "correct": 1, "level": 1},
  {"text": "Viking helmets typically featured:", "options": ["Horns", "Wings", "Neither — they were plain iron caps", "Decorative antlers"], "correct": 2, "level": 1},
  {"text": "The first country to give women the right to vote was:", "options": ["United States", "United Kingdom", "New Zealand", "Sweden"], "correct": 2, "level": 1},
  {"text": "Julius Caesar was assassinated on:", "options": ["March 13", "March 15", "March 17", "March 20"], "correct": 1, "level": 1},
  {"text": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid. True or false?", "options": ["True", "False"], "correct": 0, "level": 1},
  {"text": "The Roman Empire's official language was:", "options": ["Latin", "Greek", "Both, depending on the region", "Italian"], "correct": 2, "level": 1},
  {"text": "Which country invented the printing press?", "options": ["Italy", "China", "Germany", "Korea"], "correct": 1, "level": 1},
  {"text": "The Black Death originated in:", "options": ["Europe", "the Middle East", "Central Asia", "India"], "correct": 2, "level": 1},
  {"text": "Which empire was the largest in history by land area?", "options": ["Roman Empire", "British Empire", "Mongol Empire", "Ottoman Empire"], "correct": 1, "level": 1},
  {"text": "Einstein failed mathematics at school. True or false?", "options": ["True", "False"], "correct": 1, "level": 1},
  {"text": "The Aztec capital Tenochtitlan was built:", "options": ["On a mountain", "On an island in a lake", "In a jungle clearing", "On a coastal cliff"], "correct": 1, "level": 1},
  {"text": "Which country was the first to send a satellite into orbit?", "options": ["United States", "Soviet Union", "China", "United Kingdom"], "correct": 1, "level": 1},
  {"text": "The Hundred Years' War was fought between:", "options": ["England and Spain", "France and the Holy Roman Empire", "England and France", "France and the Papacy"], "correct": 2, "level": 1},
  {"text": "Which ancient wonder of the world survived into the modern era?", "options": ["The Colossus of Rhodes", "The Lighthouse of Alexandria", "The Great Pyramid of Giza", "The Hanging Gardens of Babylon"], "correct": 2, "level": 1},
  {"text": "Which war lasted the longest in recorded history?", "options": ["The Hundred Years' War", "The Reconquista", "The Byzantine-Arab Wars", "The Anglo-French Wars"], "correct": 1, "level": 1},
  {"text": "The Roman Empire's official language was:", "options": ["Latin only", "Greek only", "Both Latin and Greek", "Aramaic"], "correct": 2, "level": 1},

  // --- New questions ---
  {"text": "Mahatma Gandhi was nominated for the Nobel Peace Prize:", "options": ["Never", "Once", "Three times", "Five times"], "correct": 3, "level": 1},
  {"text": "The first European to reach India by sea was:", "options": ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Bartolomeu Dias"], "correct": 2, "level": 1},
  {"text": "Oxford University is older than the Aztec Empire. True or false?", "options": ["True", "False"], "correct": 0, "level": 1},
  {"text": "Which ancient civilization built Machu Picchu?", "options": ["Aztec", "Maya", "Inca", "Olmec"], "correct": 2, "level": 1},
  {"text": "The first programmable computer was invented in:", "options": ["The United States", "The United Kingdom", "Germany", "France"], "correct": 2, "level": 1},
  {"text": "Sherlock Holmes never actually said 'Elementary, my dear Watson' in any of Arthur Conan Doyle's stories. True or false?", "options": ["True", "False"], "correct": 0, "level": 1},
  {"text": "Which country lost the most soldiers in World War I as a percentage of its population?", "options": ["France", "Germany", "Serbia", "Russia"], "correct": 2, "level": 1},
  {"text": "The largest naval battle in history was:", "options": ["The Battle of Trafalgar", "The Battle of Jutland", "The Battle of Leyte Gulf", "The Battle of Midway"], "correct": 2, "level": 1},
  {"text": "Which empire controlled the most of the world's population at its peak?", "options": ["British Empire", "Mongol Empire", "Roman Empire", "Ottoman Empire"], "correct": 0, "level": 1},
  {"text": "The ancient Egyptians shaved their eyebrows when:", "options": ["Going to war", "Their cat died", "Getting married", "Becoming a pharaoh"], "correct": 1, "level": 1},
  {"text": "The first person to circumnavigate the globe was:", "options": ["Ferdinand Magellan", "Juan Sebastián Elcano", "Francis Drake", "Vasco da Gama"], "correct": 1, "level": 1},
  {"text": "Which country has the oldest written constitution still in use?", "options": ["United Kingdom", "France", "United States", "Sweden"], "correct": 2, "level": 1},
  {"text": "The Trojan War, if it happened, most likely took place around:", "options": ["500 BC", "1200 BC", "800 BC", "300 BC"], "correct": 1, "level": 1},
  {"text": "Genghis Khan's real name was:", "options": ["Genghis", "Temujin", "Kublai", "Batu"], "correct": 1, "level": 1},
  {"text": "The first Olympic Games were held in:", "options": ["Athens", "Sparta", "Olympia", "Corinth"], "correct": 2, "level": 1},
  {"text": "Which country built the first ironclad warship?", "options": ["United Kingdom", "United States", "France", "Korea"], "correct": 3, "level": 1},
  {"text": "The Colosseum in Rome could hold approximately how many spectators?", "options": ["20,000", "50,000", "100,000", "150,000"], "correct": 1, "level": 1},
  {"text": "Which US president served the shortest term?", "options": ["James Garfield", "Zachary Taylor", "William Henry Harrison", "Warren Harding"], "correct": 2, "level": 1},
  {"text": "The first country to abolish slavery was:", "options": ["United States", "United Kingdom", "Haiti", "France"], "correct": 2, "level": 1},
  {"text": "Which ancient civilization invented chess?", "options": ["Chinese", "Indian", "Persian", "Arab"], "correct": 1, "level": 1},
  {"text": "The Berlin Wall fell in:", "options": ["1987", "1988", "1989", "1990"], "correct": 2, "level": 1},
  {"text": "Which country has been invaded the most times in history?", "options": ["France", "Poland", "China", "India"], "correct": 0, "level": 1},
  {"text": "The Silk Road primarily connected:", "options": ["China and India", "China and Rome", "India and Persia", "Rome and Egypt"], "correct": 1, "level": 1},
  {"text": "Which pharaoh built the Great Pyramid of Giza?", "options": ["Ramses II", "Tutankhamun", "Khufu", "Akhenaten"], "correct": 2, "level": 1},
  {"text": "The Magna Carta was signed in:", "options": ["1066", "1215", "1348", "1453"], "correct": 1, "level": 1},
  {"text": "Which country lost the most civilians in World War II?", "options": ["Germany", "Soviet Union", "China", "Poland"], "correct": 1, "level": 1},
  {"text": "The first city in history to reach a population of one million was:", "options": ["Rome", "Alexandria", "Babylon", "Constantinople"], "correct": 0, "level": 1},
  {"text": "Rasputin survived multiple assassination attempts before finally dying. True or false?", "options": ["True", "False"], "correct": 0, "level": 1},
  {"text": "The longest siege in military history lasted approximately:", "options": ["5 years", "10 years", "21 years", "50 years"], "correct": 2, "level": 1},
  {"text": "Which country was the first to use chemical weapons in World War I?", "options": ["Germany", "France", "United Kingdom", "Austria-Hungary"], "correct": 0, "level": 1},
  {"text": "The ancient Romans used urine to:", "options": ["Tan leather and whiten teeth", "Dye fabric", "Make concrete", "Preserve food"], "correct": 0, "level": 1},
  {"text": "Which civilization built Stonehenge?", "options": ["The Celts", "The Druids", "Pre-Celtic Britons", "The Romans"], "correct": 2, "level": 1},
  {"text": "The first woman to win a Nobel Prize was:", "options": ["Marie Curie", "Bertha von Suttner", "Selma Lagerlöf", "Jane Addams"], "correct": 0, "level": 1},
  {"text": "The shortest war in history lasted approximately:", "options": ["38 minutes", "6 hours", "2 days", "1 week"], "correct": 0, "level": 1},
  {"text": "Which ancient civilization invented the wheel?", "options": ["Egyptian", "Mesopotamian", "Chinese", "Indus Valley"], "correct": 1, "level": 1},
  {"text": "The Titanic sank in:", "options": ["1910", "1911", "1912", "1913"], "correct": 2, "level": 1},
  {"text": "Which country was the first to use paper money?", "options": ["Egypt", "Rome", "China", "India"], "correct": 2, "level": 1},
  {"text": "The samurai class was officially abolished in Japan in:", "options": ["1853", "1868", "1876", "1912"], "correct": 2, "level": 1},
  {"text": "Which explorer reached Australia before Captain Cook?", "options": ["No one — Cook was the first", "The Dutch", "The Portuguese", "The Spanish"], "correct": 1, "level": 1},
  {"text": "The first trans-Atlantic telegraph cable was successfully laid in:", "options": ["1844", "1858", "1866", "1872"], "correct": 2, "level": 1},
  {"text": "Which country dropped the first atomic bomb?", "options": ["Soviet Union", "United Kingdom", "United States", "Germany"], "correct": 2, "level": 1},
  {"text": "The ancient Greek city-state of Sparta was primarily located in:", "options": ["Northern Greece", "Central Greece", "Southern Greece", "The Greek islands"], "correct": 2, "level": 1},
  {"text": "Which empire was destroyed by Hernán Cortés?", "options": ["Inca", "Maya", "Aztec", "Olmec"], "correct": 2, "level": 1},
  {"text": "The French Revolution began in:", "options": ["1787", "1788", "1789", "1790"], "correct": 2, "level": 1},
  {"text": "Which ancient civilization built the first known legal code?", "options": ["Egyptian", "Babylonian", "Sumerian", "Persian"], "correct": 2, "level": 1},
  {"text": "Abraham Lincoln was the tallest US president at:", "options": ["6'2\"", "6'3\"", "6'4\"", "6'5\""], "correct": 2, "level": 1},
  {"text": "The Meiji Restoration in Japan occurred in:", "options": ["1848", "1858", "1868", "1878"], "correct": 2, "level": 1},
  {"text": "Which country invented gunpowder?", "options": ["Japan", "India", "China", "Persia"], "correct": 2, "level": 1},
  {"text": "The first successful powered airplane flight lasted approximately:", "options": ["12 seconds", "59 seconds", "3 minutes", "12 minutes"], "correct": 0, "level": 1},
  {"text": "Which Roman emperor famously 'fiddled while Rome burned'?", "options": ["Caligula", "Commodus", "Nero", "Caracalla"], "correct": 2, "level": 1},
  {"text": "The Byzantine Empire fell in:", "options": ["1204", "1389", "1453", "1517"], "correct": 2, "level": 1},
  {"text": "Which country was NOT part of the original Axis powers in World War II?", "options": ["Germany", "Italy", "Japan", "Hungary"], "correct": 3, "level": 1},
  {"text": "The first permanent English settlement in America was:", "options": ["Plymouth", "Boston", "Jamestown", "Roanoke"], "correct": 2, "level": 1},
  {"text": "The Peloponnesian War was fought between:", "options": ["Athens and Persia", "Athens and Sparta", "Sparta and Persia", "Greece and Rome"], "correct": 1, "level": 1},
  {"text": "Which country pioneered the Industrial Revolution?", "options": ["France", "Germany", "United Kingdom", "Belgium"], "correct": 2, "level": 1},
  {"text": "The last execution by guillotine in France took place in:", "options": ["1939", "1952", "1963", "1977"], "correct": 3, "level": 1},
  {"text": "Which ancient civilization first developed a phonetic alphabet?", "options": ["Greek", "Egyptian", "Phoenician", "Sumerian"], "correct": 2, "level": 1},
  {"text": "The construction of the Panama Canal was completed in:", "options": ["1904", "1909", "1914", "1920"], "correct": 2, "level": 1},
  {"text": "Which country had the first female head of government in the modern era?", "options": ["India", "Israel", "Sri Lanka", "United Kingdom"], "correct": 2, "level": 1},
  {"text": "The Rosetta Stone was written in how many scripts?", "options": ["Two", "Three", "Four", "Five"], "correct": 1, "level": 1},
  {"text": "Which civilization built the city of Carthage?", "options": ["Greeks", "Romans", "Phoenicians", "Berbers"], "correct": 2, "level": 1},
  {"text": "The Korean War officially ended with:", "options": ["A peace treaty", "An armistice", "A ceasefire agreement", "It has never officially ended"], "correct": 3, "level": 1},
  {"text": "Which country has the longest continuous history as a unified state?", "options": ["Egypt", "China", "India", "Japan"], "correct": 1, "level": 1},
  {"text": "The first successful vaccine was developed against:", "options": ["Smallpox", "Cholera", "Rabies", "Typhoid"], "correct": 0, "level": 1},
  {"text": "The Spanish Inquisition was established in:", "options": ["1378", "1420", "1478", "1492"], "correct": 2, "level": 1},
  {"text": "Which US state was the last to ratify the Constitution?", "options": ["New York", "Virginia", "Rhode Island", "North Carolina"], "correct": 2, "level": 1},
  {"text": "The ancient city of Pompeii was buried by the eruption of Mount Vesuvius in:", "options": ["AD 62", "AD 72", "AD 79", "AD 93"], "correct": 2, "level": 1},
  {"text": "Which country was the first to circumnavigate Africa?", "options": ["Portugal", "Spain", "Phoenicia", "Egypt"], "correct": 2, "level": 1},
  {"text": "The Treaty of Versailles, which ended World War I, was signed in:", "options": ["1918", "1919", "1920", "1921"], "correct": 1, "level": 1},
  {"text": "Which ancient wonder was located in modern-day Iraq?", "options": ["The Colossus of Rhodes", "The Hanging Gardens of Babylon", "The Lighthouse of Alexandria", "The Mausoleum at Halicarnassus"], "correct": 1, "level": 1},
  {"text": "The first country to land a probe on the Moon was:", "options": ["United States", "Soviet Union", "China", "European Union"], "correct": 1, "level": 1},
  {"text": "The Opium Wars were fought between China and:", "options": ["France", "United States", "United Kingdom", "Japan"], "correct": 2, "level": 1},
  {"text": "Which medieval Islamic scholar is often called the 'father of sociology'?", "options": ["Averroes", "Avicenna", "Ibn Khaldun", "Al-Biruni"], "correct": 2, "level": 1},
  {"text": "The Easter Rising took place in Dublin in:", "options": ["1914", "1916", "1918", "1921"], "correct": 1, "level": 1},
  {"text": "Which US president was the first to visit China?", "options": ["Eisenhower", "Kennedy", "Johnson", "Nixon"], "correct": 3, "level": 1},
  {"text": "The Thirty Years' War was primarily fought in:", "options": ["France", "Spain", "The Holy Roman Empire", "England"], "correct": 2, "level": 1},
  {"text": "The ancient city of Troy was located in modern-day:", "options": ["Greece", "Turkey", "Bulgaria", "Lebanon"], "correct": 1, "level": 1},
  {"text": "Which country was the first to develop a nuclear weapon after the United States?", "options": ["United Kingdom", "Soviet Union", "France", "China"], "correct": 1, "level": 1},
  {"text": "Which country built the first steam-powered railway locomotive?", "options": ["France", "Germany", "United Kingdom", "United States"], "correct": 2, "level": 1},
  {"text": "The ancient Macedonian king who conquered Persia was:", "options": ["Philip II", "Alexander the Great", "Pyrrhus", "Antigonus"], "correct": 1, "level": 1},

  // ── INTERMEDIATE (60 questions) ─────────────────────────────────
  // ── HARD (40 questions) ──────────────────────────────────────────
// INTERMEDIATE (60 questions) — for history readers

  {"text": "The Peace of Augsburg (1555) established which principle?", "options": ["Freedom of religion for all citizens", "Cuius regio, eius religio — rulers choose the religion of their territory", "Protestantism as the official religion of the Holy Roman Empire", "A permanent truce between Catholics and Calvinists"], "correct": 1, "level": 2},
  {"text": "The Defenestration of Prague (1618) triggered:", "options": ["The Hussite Wars", "The Thirty Years' War", "The War of the Austrian Succession", "The Seven Years' War"], "correct": 1, "level": 2},
  {"text": "Which battle ended the Napoleonic Wars?", "options": ["Leipzig", "Borodino", "Waterloo", "Austerlitz"], "correct": 2, "level": 2},
  {"text": "The Scramble for Africa occurred primarily during:", "options": ["1840–1860", "1860–1880", "1880–1900", "1900–1920"], "correct": 2, "level": 2},
  {"text": "The Decembrist Revolt of 1825 was an uprising of:", "options": ["Russian serfs", "Military officers inspired by liberal ideals", "Ukrainian separatists", "Orthodox clergy against modernization"], "correct": 1, "level": 2},
  {"text": "Which dynasty ruled China during the construction of the Grand Canal?", "options": ["Han", "Tang", "Sui", "Song"], "correct": 2, "level": 2},
  {"text": "The Congress of Vienna (1814–1815) was primarily organized by:", "options": ["Napoleon Bonaparte", "Klemens von Metternich", "Duke of Wellington", "Tsar Alexander I"], "correct": 1, "level": 2},
  {"text": "The Hanseatic League was primarily a confederation of:", "options": ["German princes", "Baltic and North Sea trading cities", "Catholic bishoprics", "Swiss cantons"], "correct": 1, "level": 2},
  {"text": "Which empire controlled Mesopotamia immediately before Alexander the Great's conquest?", "options": ["Babylonian", "Assyrian", "Achaemenid Persian", "Median"], "correct": 2, "level": 2},
  {"text": "The Taiping Rebellion (1850–1864) in China resulted in approximately how many deaths?", "options": ["500,000", "5 million", "20–30 million", "100 million"], "correct": 2, "level": 2},
  {"text": "The term 'Reconquista' refers to:", "options": ["Spanish conquest of the Americas", "Christian reconquest of the Iberian Peninsula from Muslim rulers", "Portuguese exploration of Africa", "The expulsion of the Moors from Sicily"], "correct": 1, "level": 2},
  {"text": "The first Crusade was called by Pope Urban II in:", "options": ["1054", "1095", "1099", "1147"], "correct": 1, "level": 2},
  {"text": "Which Byzantine emperor codified Roman law into the Corpus Juris Civilis?", "options": ["Constantine I", "Theodosius II", "Justinian I", "Heraclius"], "correct": 2, "level": 2},
  {"text": "The Meiji Restoration replaced which ruling structure?", "options": ["The imperial court", "The Tokugawa shogunate", "The daimyo council", "The Buddhist clergy"], "correct": 1, "level": 2},
  {"text": "The Zulu Kingdom reached its peak power under:", "options": ["Dingane", "Cetshwayo", "Shaka", "Mpande"], "correct": 2, "level": 2},
  {"text": "The Edict of Nantes (1598) granted religious toleration to which group in France?", "options": ["Catholics in Protestant regions", "Huguenots (French Protestants)", "Jews", "Anabaptists"], "correct": 1, "level": 2},
  {"text": "Which naval battle marked the decisive defeat of the Spanish Armada?", "options": ["There was no single decisive battle — the Armada was scattered by storms", "The Battle of Gravelines", "The Battle of Plymouth Sound", "The Battle of the Azores"], "correct": 0, "level": 2},
  {"text": "The Safavid dynasty made which branch of Islam the state religion of Persia?", "options": ["Sunni", "Shia", "Sufi", "Ismaili"], "correct": 1, "level": 2},
  {"text": "The Opium Wars forced China to cede which territory to Britain?", "options": ["Macau", "Taiwan", "Hong Kong Island", "Shanghai"], "correct": 2, "level": 2},
  {"text": "Which African kingdom controlled the gold-salt trade across the Sahara between the 9th and 11th centuries?", "options": ["Mali Empire", "Ghana Empire", "Songhai Empire", "Kingdom of Kush"], "correct": 1, "level": 2},
  {"text": "The philosopher who tutored Alexander the Great was:", "options": ["Plato", "Socrates", "Aristotle", "Isocrates"], "correct": 2, "level": 2},
  {"text": "The Sykes-Picot Agreement (1916) secretly divided which region between Britain and France?", "options": ["North Africa", "The Arabian Peninsula", "The Levant and Mesopotamia", "Anatolia"], "correct": 2, "level": 2},
  {"text": "Which war ended with the Treaty of Portsmouth (1905), mediated by Theodore Roosevelt?", "options": ["The Boxer Rebellion", "The First Sino-Japanese War", "The Russo-Japanese War", "The Second Boer War"], "correct": 2, "level": 2},
  {"text": "The Carolingian Renaissance was a cultural revival associated with:", "options": ["Frederick Barbarossa", "Charlemagne", "Louis IX", "Otto I"], "correct": 1, "level": 2},
  {"text": "What was the primary cause of the Peloponnesian War?", "options": ["Persian interference in Greek affairs", "Athens' growing imperial power threatening Sparta and its allies", "A trade dispute over grain routes", "Religious conflict between Olympian cults"], "correct": 1, "level": 2},
  {"text": "The Mughal Empire was founded by:", "options": ["Akbar", "Babur", "Humayun", "Timur"], "correct": 1, "level": 2},
  {"text": "The Berlin Conference of 1884–1885 was convened to:", "options": ["Establish the Triple Alliance", "Regulate European colonization of Africa", "Resolve the Franco-Prussian border dispute", "Create the International Red Cross"], "correct": 1, "level": 2},
  {"text": "Which Chinese dynasty was the first to unify the country under a single emperor?", "options": ["Han", "Zhou", "Qin", "Shang"], "correct": 2, "level": 2},
  {"text": "The 'Shot heard round the world' refers to the opening of:", "options": ["The French Revolution", "The American Civil War", "The American Revolutionary War", "The War of 1812"], "correct": 2, "level": 2},
  {"text": "Which medieval pope excommunicated Holy Roman Emperor Henry IV?", "options": ["Innocent III", "Gregory VII", "Urban II", "Boniface VIII"], "correct": 1, "level": 2},
  {"text": "The Achaemenid Persian Empire was founded by:", "options": ["Darius I", "Xerxes I", "Cyrus the Great", "Cambyses II"], "correct": 2, "level": 2},
  {"text": "The Chartist movement in 19th-century Britain primarily demanded:", "options": ["Abolition of slavery", "Free trade", "Political reforms including universal male suffrage", "Repeal of the Corn Laws"], "correct": 2, "level": 2},
  {"text": "Which battle in 732 AD is credited with halting the Muslim advance into Western Europe?", "options": ["Battle of Poitiers (Tours)", "Battle of Roncevaux Pass", "Battle of the Marne", "Battle of Covadonga"], "correct": 0, "level": 2},
  {"text": "The Japanese attack on Pearl Harbor took place on:", "options": ["December 7, 1941", "December 7, 1942", "December 11, 1941", "November 7, 1941"], "correct": 0, "level": 2},
  {"text": "The Khmer Empire's capital was:", "options": ["Phnom Penh", "Angkor", "Sukhothai", "Ayutthaya"], "correct": 1, "level": 2},
  {"text": "The Non-Aligned Movement was co-founded at the Bandung Conference in 1955 by leaders including:", "options": ["Nehru, Nasser, and Tito", "Nehru, Mao, and Nkrumah", "Tito, Castro, and Sukarno", "Nasser, Ho Chi Minh, and Lumumba"], "correct": 0, "level": 2},
  {"text": "Which Roman general crossed the Rubicon in 49 BC?", "options": ["Pompey", "Sulla", "Julius Caesar", "Mark Antony"], "correct": 2, "level": 2},
  {"text": "The Warring States period in China preceded the unification under:", "options": ["The Han dynasty", "The Qin dynasty", "The Zhou dynasty", "The Shang dynasty"], "correct": 1, "level": 2},
  {"text": "The Dreyfus Affair in France was primarily about:", "options": ["A financial scandal in the Third Republic", "The wrongful conviction of a Jewish army officer for treason", "A dispute between the Church and the state over education", "A political assassination"], "correct": 1, "level": 2},
  {"text": "Which Indian emperor converted to Buddhism after the Battle of Kalinga?", "options": ["Chandragupta Maurya", "Bindusara", "Ashoka", "Harsha"], "correct": 2, "level": 2},
  {"text": "The Scramble for Africa was largely triggered by Belgium's colonization of:", "options": ["Nigeria", "Congo", "Angola", "Gold Coast"], "correct": 1, "level": 2},
  {"text": "Which dynasty ruled the Ottoman Empire from its founding until its dissolution?", "options": ["Seljuk", "Timurid", "Osman (House of Osman)", "Ayyubid"], "correct": 2, "level": 2},
  {"text": "The Haitian Revolution (1791–1804) was significant because it produced:", "options": ["The first Latin American republic", "The only successful slave revolt to establish an independent nation", "The first constitutional monarchy in the Americas", "The abolition of slavery throughout the Caribbean"], "correct": 1, "level": 2},
  {"text": "Which Russian tsar issued the Emancipation Reform of 1861, freeing the serfs?", "options": ["Nicholas I", "Alexander II", "Alexander III", "Nicholas II"], "correct": 1, "level": 2},
  {"text": "The Punic Wars were fought between Rome and:", "options": ["Greece", "Carthage", "Egypt", "Macedon"], "correct": 1, "level": 2},
  {"text": "Which medieval trading network connected Europe, the Middle East, and Asia before the Ottoman expansion?", "options": ["The Silk Road alone", "The Hanseatic League", "The Venetian–Byzantine trading network", "The combined Silk Road and Indian Ocean trade routes"], "correct": 3, "level": 2},
  {"text": "The concept of 'Manifest Destiny' was used to justify:", "options": ["American entry into World War I", "US westward expansion across North America", "The Monroe Doctrine in Latin America", "The annexation of Cuba"], "correct": 1, "level": 2},
  {"text": "Which empire destroyed the Abbasid Caliphate by sacking Baghdad in 1258?", "options": ["Seljuk Turks", "Crusaders", "Mongols", "Timurids"], "correct": 2, "level": 2},
  {"text": "The Great Schism of 1054 divided Christianity between:", "options": ["Catholics and Protestants", "Roman Catholics and Eastern Orthodox", "Nestorians and Chalcedonians", "Catholics and Copts"], "correct": 1, "level": 2},
  {"text": "The Zimmermann Telegram proposed a military alliance between Germany and:", "options": ["Austria-Hungary", "The Ottoman Empire", "Mexico", "Argentina"], "correct": 2, "level": 2},
  {"text": "Which Italian city-state pioneered double-entry bookkeeping in the late medieval period?", "options": ["Venice", "Genoa", "Florence", "Milan"], "correct": 2, "level": 2},
  {"text": "The word 'assassin' derives from a medieval Islamic sect known as:", "options": ["The Kharijites", "The Ismaili Nizari (the Hashashin)", "The Druze", "The Alawites"], "correct": 1, "level": 2},
  {"text": "The Battle of Legnano (1176) was significant because:", "options": ["It ended the First Crusade", "The Lombard League defeated Frederick Barbarossa, checking imperial power in Italy", "It marked the first use of gunpowder in Europe", "It united the Italian city-states"], "correct": 1, "level": 2},
  {"text": "The Maratha Empire at its peak controlled most of:", "options": ["Southern India only", "The Indian subcontinent from the Deccan to the north", "Bengal and Bihar", "The Indus Valley region"], "correct": 1, "level": 2},
  {"text": "Which treaty ended the Thirty Years' War?", "options": ["The Treaty of Utrecht", "The Peace of Westphalia", "The Peace of Augsburg", "The Treaty of Münster alone"], "correct": 1, "level": 2},
  {"text": "The term 'Dark Ages' for early medieval Europe was coined by:", "options": ["Edward Gibbon", "Petrarch", "Voltaire", "Montesquieu"], "correct": 1, "level": 2},
  {"text": "The Almohad dynasty originated in:", "options": ["Egypt", "Al-Andalus (Spain)", "North Africa (Maghreb)", "The Arabian Peninsula"], "correct": 2, "level": 2},
  {"text": "Which Chinese invention, adopted in Europe, fundamentally changed medieval warfare?", "options": ["The crossbow", "Gunpowder", "The stirrup", "Chain mail"], "correct": 1, "level": 2},
  {"text": "The Stono Rebellion of 1739 was one of the largest slave uprisings in:", "options": ["Haiti", "Brazil", "Colonial North America", "Jamaica"], "correct": 2, "level": 2},
  {"text": "The Dual Monarchy of Austria-Hungary was established in:", "options": ["1848", "1856", "1867", "1871"], "correct": 2, "level": 2},
  {"text": "The Scramble for Africa left which two African nations independent by 1914?", "options": ["Ethiopia and Liberia", "Ethiopia and Egypt", "Liberia and Morocco", "South Africa and Ethiopia"], "correct": 0, "level": 3},

// HARD (40 questions) — for scholars

  {"text": "The Investiture Controversy was resolved by the Concordat of Worms (1122), which established:", "options": ["Papal supremacy over all secular rulers", "A distinction between spiritual investiture (by the Pope) and temporal investiture (by the emperor)", "The right of kings to appoint all bishops", "The separation of German church from Rome"], "correct": 1, "level": 3},
  {"text": "The Anatolian hypothesis in Indo-European linguistics, proposed by Colin Renfrew, locates the Proto-Indo-European homeland in:", "options": ["The Pontic steppe", "Anatolia, spreading with the Neolithic agricultural revolution", "The Caucasus mountains", "The Iranian plateau"], "correct": 1, "level": 3},
  {"text": "The term 'Second Serfdom' describes the intensification of serfdom in Eastern Europe during the 16th–18th centuries, primarily driven by:", "options": ["Ottoman expansion disrupting trade routes", "Demand for grain exports to Western Europe via Baltic trade", "The Protestant Reformation weakening noble authority", "Demographic collapse from the Black Death"], "correct": 1, "level": 3},
  {"text": "The Pirenne Thesis argues that the true break between antiquity and the Middle Ages was caused by:", "options": ["The fall of the Western Roman Empire in 476", "The Arab conquests disrupting Mediterranean trade", "The Carolingian Renaissance", "The conversion of the Germanic kingdoms to Christianity"], "correct": 1, "level": 3},
  {"text": "The Donatist controversy in early Christianity concerned:", "options": ["The nature of Christ's divinity", "Whether sacraments administered by sinful clergy were valid", "The correct date of Easter", "The authority of the bishop of Rome"], "correct": 1, "level": 3},
  {"text": "Which pre-Columbian civilization built the city of Teotihuacan?", "options": ["Aztec", "Toltec", "Maya", "Its builders remain unknown — the Aztecs found it abandoned"], "correct": 3, "level": 3},
  {"text": "The Fourth Lateran Council (1215) was significant for, among other things:", "options": ["Launching the First Crusade", "Defining the doctrine of transubstantiation and mandating Jewish badge-wearing", "Condemning the Albigensian heresy only", "Establishing the Inquisition in Spain"], "correct": 1, "level": 3},
  {"text": "The Varangian Guard was an elite Byzantine unit composed of:", "options": ["Frankish knights", "Norse and later Anglo-Saxon mercenaries", "Armenian cavalry", "Turkish converts to Christianity"], "correct": 1, "level": 3},
  {"text": "The Amarna Period in ancient Egypt is associated with the religious revolution of:", "options": ["Ramses II", "Amenhotep III", "Akhenaten", "Thutmose III"], "correct": 2, "level": 3},
  {"text": "The concept of 'translatio imperii' held that:", "options": ["Conquered peoples must adopt the culture of their conquerors", "Imperial authority had been transferred from Rome to the Frankish and later German rulers", "The Pope held supreme temporal authority over all kings", "Trade routes should follow the borders of empires"], "correct": 1, "level": 3},
  {"text": "The Battle of Ain Jalut (1260) was historically significant because:", "options": ["It ended the Crusader presence in the Holy Land", "The Mamluks defeated the Mongols, halting their westward expansion", "It established Mamluk control over Egypt", "The Mongols converted to Islam after their victory"], "correct": 1, "level": 3},
  {"text": "The Devshirme system in the Ottoman Empire was:", "options": ["A tax on non-Muslim merchants", "The forced recruitment of Christian boys to serve in the Ottoman administration and janissary corps", "A system of land grants to military commanders", "The conversion of churches into mosques"], "correct": 1, "level": 3},
  {"text": "The Albigensian Crusade (1209–1229) was directed against:", "options": ["Heretics in southern France (Cathars)", "Muslims in the Iberian Peninsula", "Orthodox Christians in the Balkans", "Pagan Lithuanians"], "correct": 0, "level": 3},
  {"text": "Which Sassanid Persian king defeated and captured the Roman Emperor Valerian in 260 AD?", "options": ["Ardashir I", "Shapur I", "Khosrow I", "Yazdegerd III"], "correct": 1, "level": 3},
  {"text": "The 'Domesday Book' (1086) was commissioned by William the Conqueror primarily to:", "options": ["Record Norman land grants for prestige", "Assess taxable landholdings and resources across England", "Document English customs and laws", "List the names of all Anglo-Saxon nobles"], "correct": 1, "level": 3},
  {"text": "The Achaemenid Royal Road connected Susa to:", "options": ["Babylon", "Persepolis", "Sardis in Anatolia", "Alexandria in Egypt"], "correct": 2, "level": 3},
  {"text": "The Nestorian controversy concerned:", "options": ["Whether Christ had one or two natures", "Whether the Virgin Mary could be called 'Theotokos' (Mother of God), implying two distinct persons in Christ", "The validity of icons in worship", "The authority of the Patriarch of Constantinople"], "correct": 1, "level": 3},
  {"text": "The Harappan civilization declined around 1900 BC most likely due to:", "options": ["Aryan invasion", "Climate change and shifts in monsoon patterns affecting river systems", "Epidemic disease", "Military conquest by Mesopotamian city-states"], "correct": 1, "level": 3},
  {"text": "The Peace of Lodi (1454) is significant in Italian history because:", "options": ["It ended the Hundred Years' War in Italy", "It established a balance of power among the major Italian states, enabling decades of relative stability", "It expelled the Aragonese from Naples", "It created the Papal States as a sovereign entity"], "correct": 1, "level": 3},
  {"text": "The Ptolemaic dynasty of Egypt was ethnically:", "options": ["Egyptian", "Persian", "Macedonian Greek", "Syrian"], "correct": 2, "level": 3},
  {"text": "The Nizam al-Mulk, vizier to the Seljuk sultans, wrote which influential treatise on statecraft?", "options": ["Kitab al-Kharaj", "Siyasatnama (Book of Government)", "Muqaddimah", "Mirrors for Princes"], "correct": 1, "level": 3},
  {"text": "The War of the Spanish Succession (1701–1714) was triggered by:", "options": ["The death of Charles II of Spain without an heir, contested by Habsburg and Bourbon claimants", "Louis XIV's invasion of the Spanish Netherlands", "The expulsion of the Habsburgs from Spain by popular revolt", "A dispute over Gibraltar between England and Spain"], "correct": 0, "level": 3},
  {"text": "The Axum (Aksum) Empire, located in modern-day Ethiopia and Eritrea, was notable for being:", "options": ["The first sub-Saharan African state to mint coins and one of the earliest to adopt Christianity", "The origin point of the Bantu migrations", "The builder of Great Zimbabwe", "A major Persian Gulf trading power"], "correct": 0, "level": 3},
  {"text": "The Yellow Turban Rebellion (184 AD) contributed to the collapse of which Chinese dynasty?", "options": ["Qin", "Han", "Tang", "Song"], "correct": 1, "level": 3},
  {"text": "The Monophysite controversy, which split the early Church, concerned:", "options": ["Whether Christ was divine at all", "Whether Christ had one nature (divine) or two natures (divine and human)", "The authority of the bishop of Rome over Eastern bishops", "The correct formula for baptism"], "correct": 1, "level": 3},
  {"text": "The Treaty of Tordesillas (1494) divided the world between Spain and Portugal along:", "options": ["The equator", "A meridian 370 leagues west of the Cape Verde Islands", "The coast of Africa", "The line of the Prime Meridian"], "correct": 1, "level": 3},
  {"text": "The Fragmentation Period (Zersplitterung) of the Holy Roman Empire was characterized by:", "options": ["Constant civil war among the emperor's sons", "The increasing power of territorial princes at the expense of central imperial authority", "Repeated invasion by Mongol forces", "The dominance of the Hanseatic League over the emperor"], "correct": 1, "level": 3},
  {"text": "The Assassins (Nizari Ismailis) established their main stronghold at:", "options": ["Masyaf in Syria (only)", "Alamut in northern Persia", "Mosul in Iraq", "Aleppo in Syria"], "correct": 1, "level": 3},
  {"text": "The Pax Mongolica refers to:", "options": ["The peace treaty ending the Mongol invasions of Europe", "The relative stability and safe trade routes across Eurasia under Mongol rule in the 13th–14th centuries", "Mongol religious tolerance formalized in a charter", "A diplomatic agreement between the Mongols and the papacy"], "correct": 1, "level": 3},
  {"text": "Which pre-Columbian civilization is responsible for the Dresden Codex, one of the few surviving Maya manuscripts?", "options": ["Aztec scribes who copied Maya texts", "The Yucatec Maya", "The K'iche' Maya", "The Toltec-Maya of Chichen Itza"], "correct": 1, "level": 3},
  {"text": "The doctrine of 'Papal Infallibility' was formally defined as dogma at:", "options": ["The Council of Trent (1545–1563)", "The First Vatican Council (1869–1870)", "The Second Vatican Council (1962–1965)", "The Fourth Lateran Council (1215)"], "correct": 1, "level": 3},
  {"text": "The Gracchi brothers (Tiberius and Gaius) in the Roman Republic are associated with:", "options": ["Military reforms that professionalized the legions", "Attempts at land reform to redistribute public land to the landless poor, which led to political violence", "The conquest of North Africa", "Reforms to the Roman legal system"], "correct": 1, "level": 3},
  {"text": "The Muscovite concept of 'Third Rome' held that Moscow had inherited the spiritual role of Rome and Constantinople because:", "options": ["Moscow had the largest Orthodox cathedral in the world", "After Constantinople's fall to the Ottomans in 1453, Moscow was seen as the last great Orthodox Christian power", "The Patriarch of Constantinople had moved to Moscow", "Ivan III had conquered Constantinople briefly"], "correct": 1, "level": 3},
  {"text": "The Statute of Kilkenny (1366) in medieval Ireland attempted to:", "options": ["Establish English common law throughout Ireland", "Prevent the Anglo-Norman settlers from adopting Irish language, customs, and laws", "Grant self-governance to Irish chieftains", "Formally annex Ireland to the English crown"], "correct": 1, "level": 3},
  {"text": "The Eurasian steppe nomads known as the Scythians were eventually largely displaced by:", "options": ["The Persian Achaemenid Empire", "The Sarmatians", "The Huns", "Alexander the Great's successors"], "correct": 1, "level": 3},
  {"text": "The Nerchinsk Treaty of 1689, the first formal treaty between Russia and China, settled:", "options": ["Trade rights along the Silk Road", "The border in the Amur River region and terms of trade", "Russian access to Chinese ports", "The status of Russian Orthodox missionaries in China"], "correct": 1, "level": 3},
  {"text": "The Crusader state known as the County of Edessa was the first to fall, in:", "options": ["1099", "1144", "1187", "1204"], "correct": 1, "level": 3},
  {"text": "The Mfecane (or Difaqane) of the early 19th century in southern Africa refers to:", "options": ["The Great Trek of Boer settlers northward", "A period of widespread warfare and forced migration among Bantu-speaking peoples, partly associated with Zulu expansion", "The British annexation of the Cape Colony", "The collapse of the Rozvi Empire"], "correct": 1, "level": 3},
  {"text": "The philosopher and statesman who wrote 'The Prince' was Niccolò Machiavelli, but his less-read 'Discourses on Livy' argued in favor of:", "options": ["Absolute monarchy as the most stable form of government", "Republican government as superior to principalities for long-term stability", "Theocracy as the ideal Florentine constitution", "Aristocratic oligarchy on the Venetian model"], "correct": 1, "level": 3},
];